//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteOperacionMantenimiento.SistemaAlarmasSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SistemaAlarmasSR.IServiciosMantenimiento")]
    public interface IServiciosMantenimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/GetClientes", ReplyAction="http://tempuri.org/IServiciosMantenimiento/GetClientesResponse")]
        System.Collections.Generic.List<string> GetClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/GetClientes", ReplyAction="http://tempuri.org/IServiciosMantenimiento/GetClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/GetAlarmasConfiguradas", ReplyAction="http://tempuri.org/IServiciosMantenimiento/GetAlarmasConfiguradasResponse")]
        System.Collections.Generic.List<string> GetAlarmasConfiguradas(string idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/GetAlarmasConfiguradas", ReplyAction="http://tempuri.org/IServiciosMantenimiento/GetAlarmasConfiguradasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAlarmasConfiguradasAsync(string idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/ModificarAlarma", ReplyAction="http://tempuri.org/IServiciosMantenimiento/ModificarAlarmaResponse")]
        void ModificarAlarma(LogicaNegocio.Alarma a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/ModificarAlarma", ReplyAction="http://tempuri.org/IServiciosMantenimiento/ModificarAlarmaResponse")]
        System.Threading.Tasks.Task ModificarAlarmaAsync(LogicaNegocio.Alarma a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/ObtenerEstadisticas", ReplyAction="http://tempuri.org/IServiciosMantenimiento/ObtenerEstadisticasResponse")]
        System.Collections.Generic.List<int> ObtenerEstadisticas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosMantenimiento/ObtenerEstadisticas", ReplyAction="http://tempuri.org/IServiciosMantenimiento/ObtenerEstadisticasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> ObtenerEstadisticasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosMantenimientoChannel : ClienteOperacionMantenimiento.SistemaAlarmasSR.IServiciosMantenimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosMantenimientoClient : System.ServiceModel.ClientBase<ClienteOperacionMantenimiento.SistemaAlarmasSR.IServiciosMantenimiento>, ClienteOperacionMantenimiento.SistemaAlarmasSR.IServiciosMantenimiento {
        
        public ServiciosMantenimientoClient() {
        }
        
        public ServiciosMantenimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosMantenimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosMantenimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosMantenimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetClientes() {
            return base.Channel.GetClientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClientesAsync() {
            return base.Channel.GetClientesAsync();
        }
        
        public System.Collections.Generic.List<string> GetAlarmasConfiguradas(string idCliente) {
            return base.Channel.GetAlarmasConfiguradas(idCliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAlarmasConfiguradasAsync(string idCliente) {
            return base.Channel.GetAlarmasConfiguradasAsync(idCliente);
        }
        
        public void ModificarAlarma(LogicaNegocio.Alarma a) {
            base.Channel.ModificarAlarma(a);
        }
        
        public System.Threading.Tasks.Task ModificarAlarmaAsync(LogicaNegocio.Alarma a) {
            return base.Channel.ModificarAlarmaAsync(a);
        }
        
        public System.Collections.Generic.List<int> ObtenerEstadisticas() {
            return base.Channel.ObtenerEstadisticas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> ObtenerEstadisticasAsync() {
            return base.Channel.ObtenerEstadisticasAsync();
        }
    }
}
